language: ruby
rvm:
  - 1.8.7
  - 1.9.2
before_script:
  - 'git clone git://github.com/saz/puppet-ssh spec/fixtures/modules/ssh'
  - 'git clone git://github.com/puppetlabs/puppetlabs-rsync spec/fixtures/modules/rsync'
  - 'git clone git://github.com/saz/puppet-memcached spec/fixtures/modules/memcached'
  - 'git clone git://github.com/puppetlabs/puppetlabs-stdlib spec/fixtures/modules/stdlib'
  - 'git clone git://github.com/puppetlabs/puppet-apt spec/fixtures/modules/apt'
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.6.12
  - PUPPET_VERSION=2.7.6
  - PUPPET_VERSION=2.7.11
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.12
